default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, pre-push]
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push]
      - id: mixed-line-ending
        stages: [pre-commit, pre-push]
      - id: check-yaml
        stages: [pre-commit, pre-push]
      - id: sort-simple-yaml
        stages: [pre-commit, pre-push]
      - id: check-added-large-files
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: bump-version
        name: Bump package version
        entry: bash -c "npm version patch --no-git-tag-version && git add package.json package-lock.json"
        language: system
        pass_filenames: false
        files: \.(ts|tsx|js|jsx|json)$
        stages: [pre-commit]
